name: devnet-genesis

services:
  custom-geth-genesis:
    image: "node:20-alpine"
    working_dir: /genesis
    # 2.24.0 required
    env_file:
      - path: .env
        required: false
    volumes:
      - ./genesis:/genesis
      - ./data/geth:/geth
      - ./config:/config:ro
    entrypoint: ["node", "index.mjs"]

  create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl"
    command:
      - testnet
      - generate-genesis
      - --fork=deneb
      - --num-validators=3
      - --genesis-time-delay=10
      - --chain-config-file=/config/config.yml
      - --geth-genesis-json-in=/geth/genesis.json
      - --geth-genesis-json-out=/geth/genesis.json
      - --output-ssz=/prysm/genesis.ssz
    volumes:
      - ./data/geth:/geth
      - ./data/prysm:/prysm
      - ./config/config.yml:/config/config.yml:ro
    depends_on:
      custom-geth-genesis:
        condition: service_completed_successfully

  init-geth-genesis:
    image: "ethereum/client-go:v1.14.4"
    command: init --cache.preimages=true --datadir /geth /geth/genesis.json
    volumes:
      - ./data/geth:/geth
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully
